import React, { createContext, useState } from "react";
export const AppContext = createContext();

const AppProvider = (props) => {
  const [status, setStatus] = useState("inbox");
  const [emails, setEmails] = useState([
    {
      id: 1,
      from: "Amazon",
      subject: "Welcome to Gmail Clone",
      body: "This is a sample email body.",
      date: "2025-07-20",
      starred: false,
      important: false,
      sent: false,
      inbox: true,
    },
    {
      id: 2,
      from: "Flipkart",
      subject: "Your Order Has Shipped",
      body: "Your order is on the way!",
      date: "2025-07-19",
      starred: false,
      important: false,
      sent: false,
      inbox: true,
    },
    {
      id: 3,
      from: "GitHub",
      subject: "Repository Starred",
      body: "You have starred a new repository.",
      date: "2025-07-18",
      starred: true,
      important: false,
      sent: false,
      inbox: true,
    },
    {
      id: 4,
      from: "Google",
      subject: "Security Alert",
      body: "New sign-in to your account.",
      date: "2025-07-17",
      starred: false,
      important: true,
      sent: false,
      inbox: true,
    },
    {
      id: 5,
      from: "Friend",
      subject: "Meeting Confirmation",
      body: "Looking forward to our meeting.",
      date: "2025-07-16",
      starred: false,
      important: false,
      sent: true,
      inbox: false,
    },
    {
      id: 6,
      from: "LinkedIn",
      subject: "Job Opportunity",
      body: "A new job matches your profile.",
      date: "2025-07-15",
      starred: true,
      important: false,
      sent: false,
      inbox: true,
    },
    {
      id: 7,
      from: "Bank",
      subject: "Account Statement",
      body: "Your monthly statement is ready.",
      date: "2025-07-14",
      starred: false,
      important: true,
      sent: false,
      inbox: true,
    },
    {
      id: 8,
      from: "Brother",
      subject: "Follow Up",
      body: "Just checking in on our last conversation.",
      date: "2025-07-13",
      starred: false,
      important: false,
      sent: true,
      inbox: false,
    },
    {
      id: 9,
      from: "Netflix",
      subject: "Subscription Update",
      body: "Your subscription has been renewed.",
      date: "2025-07-12",
      starred: false,
      important: false,
      sent: false,
      inbox: true,
    },
    {
      id: 10,
      from: "Spotify",
      subject: "Playlist Recommendation",
      body: "Check out this new playlist!",
      date: "2025-07-11",
      starred: false,
      important: false,
      sent: false,
      inbox: true,
    },
    {
      id: 11,
      from: "Microsoft",
      subject: "Update Available",
      body: "A new update is ready to install.",
      date: "2025-07-10",
      starred: true,
      important: false,
      sent: false,
      inbox: true,
    },
    {
      id: 12,
      from: "Apple",
      subject: "Your Invoice",
      body: "Your invoice for July.",
      date: "2025-07-09",
      starred: false,
      important: true,
      sent: false,
      inbox: true,
    },
    {
      id: 13,
      from: "Tesla",
      subject: "Service Reminder",
      body: "Your car service is due.",
      date: "2025-07-08",
      starred: false,
      important: false,
      sent: true,
      inbox: false,
    },
    {
      id: 14,
      from: "SpaceX",
      subject: "Launch Notification",
      body: "A new launch is scheduled.",
      date: "2025-07-07",
      starred: true,
      important: true,
      sent: false,
      inbox: true,
    },
    {
      id: 15,
      from: "Uber",
      subject: "Ride Receipt",
      body: "Your ride receipt for July.",
      date: "2025-07-06",
      starred: false,
      important: false,
      sent: false,
      inbox: true,
    },
    {
      id: 16,
      from: "Ola",
      subject: "Ride Cancelled",
      body: "Your ride was cancelled.",
      date: "2025-07-05",
      starred: false,
      important: true,
      sent: false,
      inbox: true,
    },
    {
      id: 17,
      from: "Paytm",
      subject: "Wallet Recharge",
      body: "Your wallet has been recharged.",
      date: "2025-07-04",
      starred: true,
      important: false,
      sent: false,
      inbox: true,
    },
    {
      id: 18,
      from: "Swiggy",
      subject: "Order Delivered",
      body: "Your food order has been delivered.",
      date: "2025-07-03",
      starred: false,
      important: false,
      sent: true,
      inbox: false,
    },
    {
      id: 19,
      from: "Zomato",
      subject: "Order Cancelled",
      body: "Your order was cancelled.",
      date: "2025-07-02",
      starred: false,
      important: true,
      sent: false,
      inbox: true,
    },
    {
      id: 20,
      from: "IRCTC",
      subject: "Ticket Booked",
      body: "Your train ticket is booked.",
      date: "2025-07-01",
      starred: true,
      important: false,
      sent: false,
      inbox: true,
    },
    {
      id: 21,
      from: "Airbnb",
      subject: "Booking Confirmed",
      body: "Your stay is confirmed.",
      date: "2025-06-30",
      starred: false,
      important: false,
      sent: true,
      inbox: false,
    },
    {
      id: 22,
      from: "Snapdeal",
      subject: "Order Shipped",
      body: "Your order is on the way!",
      date: "2025-06-29",
      starred: false,
      important: true,
      sent: false,
      inbox: true,
    },
    {
      id: 23,
      from: "Myntra",
      subject: "Sale Alert",
      body: "Big sale starts tomorrow!",
      date: "2025-06-28",
      starred: true,
      important: false,
      sent: false,
      inbox: true,
    },
    {
      id: 24,
      from: "Jio",
      subject: "Recharge Successful",
      body: "Your Jio recharge is successful.",
      date: "2025-06-27",
      starred: false,
      important: false,
      sent: false,
      inbox: true,
    },
    {
      id: 25,
      from: "Airtel",
      subject: "Bill Due",
      body: "Your bill is due soon.",
      date: "2025-06-26",
      starred: false,
      important: true,
      sent: false,
      inbox: true,
    },
    {
      id: 26,
      from: "Vodafone",
      subject: "Plan Expiry",
      body: "Your plan expires soon.",
      date: "2025-06-25",
      starred: true,
      important: false,
      sent: false,
      inbox: true,
    },
    {
      id: 27,
      from: "Redbus",
      subject: "Bus Ticket Confirmed",
      body: "Your bus ticket is confirmed.",
      date: "2025-06-24",
      starred: false,
      important: false,
      sent: true,
      inbox: false,
    },
    {
      id: 28,
      from: "BookMyShow",
      subject: "Movie Ticket Booked",
      body: "Your movie ticket is booked.",
      date: "2025-06-23",
      starred: false,
      important: true,
      sent: false,
      inbox: true,
    },
    {
      id: 29,
      from: "HDFC Bank",
      subject: "Credit Card Statement",
      body: "Your credit card statement is ready.",
      date: "2025-06-22",
      starred: true,
      important: false,
      sent: false,
      inbox: true,
    },
    {
      id: 30,
      from: "Axis Bank",
      subject: "Loan Approved",
      body: "Your loan has been approved.",
      date: "2025-06-21",
      starred: false,
      important: false,
      sent: false,
      inbox: true,
    },
  ]);

  const sendMail = ({ to, subject, body }) => {
    setEmails((prev) => [
      ...prev,
      {
        id: prev.length ? prev[prev.length - 1].id + 1 : 1,
        from: to,
        subject,
        body,
        date: new Date().toISOString().slice(0, 10),
        starred: false,
        important: false,
        sent: true,
        inbox: false,
      },
    ]);
  };

  return (
    <AppContext.Provider
      value={{ emails, status, setStatus, sendMail, setEmails }}>
      {props.children}
    </AppContext.Provider>
  );
};

export default AppProvider;
